### ISSUE TITLE
Create a singleton object

### ISSUE THREAD

**Issue by nicodav** [42ity/fty-common#1]
One possibility is to include in this common lib a singleton object which can store any usefull informations for other agents.
2 Examples : 
-Store the id and or the uuid of the rackcontroller, so an agent can get this informations from this singleton object instead of make a request to fty-info. Of course the singleton object will make a request to fty-info the first time an agent will request this informations => less request to fty-info.

-In our case, etn-ipm1 send a message to etn-amqp to notify any changes and etn-amqp will try to send this change to an IPM1 connected to the IPC or not !.  So if the etn-amqp store the information "the ipc is connected to an IPM1" in the singleton object , the etn-ipm1 will check this information and send or not the change to etn-amqp. => less useless messages send between agents.

**Comment by EldoreiJK** [comment]
Sounds interesting, but kindly note that such a singleton object must be a shared memory object, introducing lots of semaphores for cross-process access and overriding current communication model. This seems as a major drawback, as this is the reason why database isn't used for storing such data as well.

Also note common library should be available for both C and C++. Some of the agents are written in pure C to avoid C++ overhead and use just gcc compiler, instead of g++.

**Comment by FrancoisRegisDegott-eaton** [comment]
outdated (not an issue as well)
